services:
  php-apache:
    container_name: "${CONTAINER_NAME_PREFIX}-php"
    build: ./Docker/php-apache
    volumes:
      - ${PATH_TO_API_CONTENT}:/var/www/html
    ports:
      - "80:80"
    networks:
      - fid-net

  db:
    container_name: "${CONTAINER_NAME_PREFIX}-database"
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_ROOT_USER=${ROOT_USER}
      - MYSQL_ALLOW_EMPTY_ROOT_PASSWORD=yes
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - fid-net

volumes:
  db:

networks:
  fid-net: